trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    # path('one_time/', views.my_pickups, name="my_pickups"),
    path('add_charge/<int:customer_id>/', views.add_charge, name = "add_charge"),
    path('weekly_pickup/', views.weekly_pickup, name="weekly_pickup"),   
    
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  {% load static %}
</head>
  <body class = "bg-info">
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #25b1da;">

    <a class="navbar-brand" >Trash Collector</a>
      <div class="navbar-nav">
    {% block navbar %} 
      <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
      <a class="nav-item nav-link" href="{% url 'employees:weekly_pickup' %}">Select Day</a>
      <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
    {% endblock %} 
    <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
    </div>
  </nav>
  {% endif %}
    <main>
      <br> <br>
      <center><img src="{% static 'images/image.png' %}" alt = "trash cat"></center>
      <div class="container">
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8" align="center">
            <br />
            <br />
            <h1>{% block header %}{% endblock %}</h1>
            {% block content %}{% endblock %}
          </div>
          <div class="col-2"></div>
        </div>
      </div>
    </main>
  </body>
</html>

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Trash Collector {% endblock %}

{% block header %} Trash Collector {% endblock %}

{% block content %}
<br />
<br />
<br />
<br />
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}