trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    # path('one_time/', views.my_pickups, name="my_pickups"),
    path('add_charge/<int:customer_id>/', views.add_charge, name = "add_charge"),
    path('weekly_pickup/', views.weekly_pickup, name="weekly_pickup"),   
    
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5) 

    def __str__(self):
        return self.name
    

trash_collector/employees/views.py
from django.apps import apps
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from datetime import date
import datetime
import calendar


from .models import Employee 
# from .models import Customer

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Employee = apps.get_model('employees.Employee')
    logged_in_user = request.user 
    Customer = apps.get_model('customers.Customer')
    week_days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    today = date.today()
    week_num = datetime.date.today().weekday()
    week_string = week_days[week_num]
    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=logged_in_user)
        customer_zip = Customer.objects.filter(zip_code=logged_in_employee.zip_code) 
        daily_pickups = customer_zip.filter(weekly_pickup=week_string) | customer_zip.filter(one_time_pickup=today)
        not_suspended = daily_pickups.exclude(suspend_start__lte=today, suspend_end__gte=today) #| daily_pickups.exclude(suspend_start=NULL)
        final_list = not_suspended.exclude(date_of_last_pickup=today)
        
        today = date.today()
        
        context = {
            'logged_in_employee': logged_in_employee,
            'today': today,
            'final_list' : final_list,
            
        }

        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))
    
@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, address=address_from_form, zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

def add_charge(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(id=customer_id)
    customer.balance += 20
    customer.date_of_last_pickup = date.today()
    customer.save()
    print("successful pickup")
    return HttpResponseRedirect(reverse('employees:index'))

def pick_day(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(id=customer_id)
    

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.address = address_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)

def weekly_pickup(request):
    Customer = apps.get_model('customers.Customer')
    day_of_week = request.POST.get("weekly_pickup")
    customers = Customer.objects.filter(weekly_pickup=day_of_week)
    context = {
        'final_list': customers,
    }
    return render(request, 'employees/select_day.html', context)

trash_collector/employees/templates/employees/charged.html
{% extends 'base.html' %}

{% block title %} Charge Confirmation {% endblock %}

{% block header %} Pickup Confirmation {% endblock %}

{% block content %}

<form action="{% url 'employees:index' %}" method="post">
    
    <input type="submit" value="Confirm">
</form>

{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name" value="{{logged_in_employee.name}}">
    <br />
    <br />
    Address: <input type="text" name="address" id="address" value="{{logged_in_employee.address}}">
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:weekly_pickup' %}">Select Day</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <form action="{% url 'employees:weekly_pickup' %}" method='post'>

    {% csrf_token %}
  <select name='weekly_pickup'>
    <option value='Monday'>Monday</option>
    <option value='Tuesday'>Tuesday</option>
    <option value='Wednesday'>Wednesday</option>
    <option value='Thursday'>Thursday</option>
    <option value='Friday'>Friday</option>
    <option value='Saturday'>Saturday</option>
    <option value='Sunday'>Sunday</option>
  </select>
  <button type='submit'>Pick Day</button>
    </form>
    Hello {{ logged_in_employee.name }}!<br />
    Address: {{ logged_in_employee.address }} {{logged_in_employee.zip_code }}<br /><br>
    {% for item in final_list %}
      <tr>
          <td>Customer Name: {{item.name}}</td> <td>Address: {{item.address}}</td> 
          <td>Zip Code: {{item.zip_code}}</td><a class = 'btn btn-danger'  href="{% url 'employees:add_charge' item.id %}">
            Click me</a><br><br>
      </tr>
    {% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  <br>
  <br>
  {% endif %}

{% endblock %}

trash_collector/employees/templates/employees/select_day.html
{% extends 'base.html' %}

{% block title %}{% block header %} Select Pickup Day {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <form action="{% url 'employees:weekly_pickup' %}" method='post'>

    {% csrf_token %}
  <select name='weekly_pickup'>
    <option value='Monday'>Monday</option>
    <option value='Tuesday'>Tuesday</option>
    <option value='Wednesday'>Wednesday</option>
    <option value='Thursday'>Thursday</option>
    <option value='Friday'>Friday</option>
    <option value='Saturday'>Saturday</option>
    <option value='Sunday'>Sunday</option>
  </select>
  <button type='submit'>Pick Day</button>
    </form>
    Hello {{ logged_in_employee.name }}!<br />
    Address: {{ logged_in_employee.address }} {{logged_in_employee.zip_code }}<br /><br>
    {% for item in final_list %}
      <tr>
          <td>Customer Name: {{item.name}}</td> <td>Address: {{item.address}}</td> 
          <td>Zip Code: {{item.zip_code}}</td>
      </tr>
    {% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  <br>
  <br>
  {% endif %}

{% endblock %}